# Generated by Django 5.2.1 on 2025-05-09 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recipe",
            old_name="user_id",
            new_name="author",
        ),
    ]
