# Generated by Django 5.2.1 on 2025-05-16 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "recipes",
            "0002_alter_foodgramuser_managers_foodgramuser_date_joined_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="recipe",
            options={
                "ordering": ("-id",),
                "verbose_name": "Рецепт",
                "verbose_name_plural": "Рецепты",
            },
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="create_date",
        ),
    ]
