# Generated by Django 5.2.1 on 2025-05-10 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0006_recipe_create_date_alter_recipe_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="create_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
