# Generated by Django 5.2.1 on 2025-05-10 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_subscriber"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="foodgramuser",
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
        migrations.AlterModelOptions(
            name="subscriber",
            options={"verbose_name": "Подписка", "verbose_name_plural": "Подписки"},
        ),
        migrations.AlterField(
            model_name="foodgramuser",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="avatars/"),
        ),
    ]
