# Generated by Django 5.2.1 on 2025-05-09 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0002_rename_user_id_recipe_author"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipe",
            name="ingredients",
        ),
    ]
